### ISSUE TITLE
KeyError: 'folder_key' for recursive create_folder

### ISSUE THREAD

**Issue by roman-yepishev** [MediaFire/mediafire-python-open-sdk#21]
```
mediafire.client.ResourceNotFoundError: /Duplicity/a/b/c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rye/Projects/mediafire-python-open-sdk/examples/mediafire-cli.py", line 273, in <module>
    main()
  File "/home/rye/Projects/mediafire-python-open-sdk/examples/mediafire-cli.py", line 264, in main
    result = router[args.action](client, args)
  File "/home/rye/Projects/mediafire-python-open-sdk/examples/mediafire-cli.py", line 108, in do_folder_create
    result = client.create_folder(args.uri, recursive=True)
  File "/home/rye/.local/lib/python3.4/site-packages/mediafire/client.py", line 288, in create_folder
    parent_key = result['folder_key']
KeyError: 'folder_key'
```
`folder_key` will not be in result of `folder/get_info`, it's `folderkey`

**Comment by roman-yepishev** [comment]
Fixed in 754a5a70bc16cde99dacf6a37096d66d0f1a1fb1
