### ISSUE TITLE
Cannot import mediafire.client

### ISSUE THREAD

**Issue by wiz21b** [MediaFire/mediafire-python-open-sdk#26]
Right after : 

`pip install mediafire`

=> which installed the 5.2 version successfully
```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32          
Type "help", "copyright", "credits" or "license" for more information.                                  
>>> from mediafire.client import (MediaFireClient, File, Folder)                                        
Traceback (most recent call last):                                                                      
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked                           
AttributeError: 'module' object has no attribute '__path__'                                             
                                                                                                        
During handling of the above exception, another exception occurred:                                     
                                                                                                        
Traceback (most recent call last):                                                                      
  File "<stdin>", line 1, in <module>                                                                   
ImportError: No module named 'mediafire.client'; 'mediafire' is not a package                           
```

That import comes form the documentation on PyPI.

Didn't look for solution so far.

**Comment by wiz21b** [comment]
Hmmm... It looks like I had a PYTHONPATH set... It seems to annoy the mediafire library....

**Comment by roman-yepishev** [comment]
That's because you had a file called `mediafire.py` in one of the directories specified in `PYTHONPATH`:

```
$ export PYTHONPATH=/home/rye/tmp
$ touch /home/rye/tmp/mediafire.py
$ python3 -c 'from mediafire.client import (MediaFireClient, File, Folder)'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'mediafire.client'; 'mediafire' is not a package
```
