### ISSUE TITLE
Assertion fails on len(upload_info.hash_info.units) == number_of_units

### ISSUE THREAD

**Issue by roman-yepishev** [MediaFire/mediafire-python-open-sdk#30]
```
ERROR 2016-11-14 19:37:44,391 upload: <bound method MediaFireUploader._upload_resumable of <mediafire.uploader.MediaFireUploader object at 0x7f6b4fc2e7f0>> failed
Traceback (most recent call last):
  File "/home/rye/.local/lib/python3.5/site-packages/mediafire/uploader.py", line 298, in upload
    upload_result = upload_func(upload_info, check_result)
  File "/home/rye/.local/lib/python3.5/site-packages/mediafire/uploader.py", line 540, in _upload_resumable
    assert len(upload_info.hash_info.units) == number_of_units
AssertionError
Traceback (most recent call last):
  File "./mediafire-cli.py", line 276, in <module>
    main()
  File "./mediafire-cli.py", line 267, in main
    result = router[args.action](client, args)
  File "./mediafire-cli.py", line 72, in do_file_upload
    result = client.upload_file(src_path, args.dest_uri)
  File "/home/rye/.local/lib/python3.5/site-packages/mediafire/client.py", line 496, in upload_file
    action_on_duplicate='replace')
  File "/home/rye/.local/lib/python3.5/site-packages/mediafire/uploader.py", line 312, in upload
    raise UploadError("Upload failed")
mediafire.uploader.UploadError: Upload failed
```

May be behind [LP:1641702](https://bugs.launchpad.net/duplicity/+bug/1641702).

**Comment by roman-yepishev** [comment]
Optimization from #3 turns to be no longer usable. We must obey the server which means that we will have to hash the file twice (first for the total size and `upload/resumable` call, then for individual units).
