### ISSUE TITLE
KeyError: 'filename' when uploading with MediaFireClient

### ISSUE THREAD

**Issue by JayBrown** [MediaFire/mediafire-python-open-sdk#33]
Upload works fine with the MediaFireClient, but there's still an error, and it's unable to get the share URL.

```
<bound method MediaFireUploader._upload_simple of <mediafire.uploader.MediaFireUploader object at 0x10770fd10>> failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mediafire/uploader.py", line 273, in upload
    upload_result = upload_func(upload_info, check_result)
  File "/usr/local/lib/python3.7/site-packages/mediafire/uploader.py", line 432, in _upload_simple
    return self._poll_upload(upload_key, 'upload/simple')
  File "/usr/local/lib/python3.7/site-packages/mediafire/uploader.py", line 319, in _poll_upload
    doupload['description'], doupload['filename'],
KeyError: 'filename'
```

Doing this on macOS 10.14.6 with python3 using `client.upload_file(filepath, "mf:/" + uldir + "/")`, then checking the URL with:

```
fileinfo = client.get_resource_by_path("/" + uldir + "/" + filepathbase)
dlurl = fileinfo['links']['normal_download']
dlurl = dlurl.replace('http:', 'https:')
print(dlurl)
```

Not sure where the error occurs: either in the `upload_file` function, or in the `get_resource_by_path` function.

**Comment by JayBrown** [comment]
Just tested a variant, where the script ignores the error by the upload function (which it is), but it's still not able to `get_resource_by_path`. It seems like the API or this SDK is broken or incompatible. (?)

The file is there & was uploaded correctly, but it's super buggy. No output with the final URL.

**Comment by kot7k** [comment]
I have the same problem, have been  trying to fix it for some time removing some checks but it keeps reapearing...
The things is that is difficult to debug cause it suddenly starts uploading everything fine and when you try it the next day it doesn´t work again.

**Comment by JayBrown** [comment]
Yep, sometimes it works, sometimes it doesn't. One alternative might be to use api.py instead of client.py. Maybe that's more stable. But I'm not sure when I'll get around to it.

**Comment by JayBrown** [comment]
Another thing I just noticed which might be a workaround: if you upload one file using the MediaFireClient, you often get an error, but if you upload another file afterwards, it tends to work OK. So maybe we have to just upload a small placeholder file first, and only then the actual files we want to upload. Will have to test this further.

**Comment by JayBrown** [comment]
Well, that didn't work, but I might have found the reason for the error: the MediaFire server apparently calculates the checksum of your file after upload, and with bigger files that might take longer, so you won't get an "upload success" notice, and your upload routine will seemingly fail. So if I upload a bigger file, I usually get an error; upload it again immediately afterwards, and the server will not allow it & produce an error, probably because the file is already there, but it's still calculating the checksum. But after some time, the server will have finished the calculations, and if (in your upload script) you do the same locally, e.g. with

```
import hashlib
sha256_hash = hashlib.sha256()
with open(filepath,"rb") as f:
	for byte_block in iter(lambda: f.read(4096),b""):
		sha256_hash.update(byte_block)
	localhash = sha256_hash.hexdigest()
```

…and ask for the checksum from the server, and compare the two, e.g. with

```
fileinfo = client.get_resource_by_path("/" + filepathbase)
remotehash = fileinfo['hash']
if localhash == remotehash:
```

…then you'll have proof that the upload was successful, and then you can just grab the public URL of the file:

```
dlurl = fileinfo['links']['normal_download']
dlurl = dlurl.replace('http://www.', 'https://')
```

**Comment by kot7k** [comment]
Hi, im just attaching my modified uploader.py in case it is useful for somebody. I just tried to remove all the conditions that check if upload was successful as it was the part wich was failing and it always end up uploading the file without errors (at least in my case). I just tested it and it's working right now although i can't guarantee that it is always going to work.
As i said i only tried to remove the conditions that check if the file was properly uploaded wich **is not a propper fix**, but at least it's working for me right now.
[uploader.zip](https://github.com/MediaFire/mediafire-python-open-sdk/files/3842642/uploader.zip)

Note: i don't even remember if i modified more files than this one.
