### ISSUE TITLE
`openshot.profile` needs update for `openshot` 2.5.0

### ISSUE THREAD

**Issue by jose1711** [MediaFire/mediafire-python-open-sdk#35]
`openshot-qt` gives errors and is unable to present file selection dialog on arch linux with the current 2.5.0 version.
stdout/stderr:
```
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
      logger:ERROR Exception in thread
     version:ERROR Failed to get version from: http://www.openshot.org/version/json/
      logger:ERROR Thread-5
      logger:ERROR :
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      logger:ERROR self.run()
      logger:ERROR   File "/usr/lib/python3.8/site-packages/openshot_qt/classes/thumbnail.py", line 98, in run
files_listview:INFO currentChanged
      logger:ERROR self.server_address = ('127.0.0.1', self.find_free_port())
files_listview:INFO updateSelection
      logger:ERROR   File "/usr/lib/python3.8/site-packages/openshot_qt/classes/thumbnail.py", line 83, in find_free_port
 files_model:INFO updating files model.
      logger:ERROR s = socket.socket()
      logger:ERROR   File "/usr/lib/python3.8/socket.py", line 231, in __init__
      logger:ERROR _socket.socket.__init__(self, family, type, proto, fileno)
      logger:ERROR OSError
      logger:ERROR :
      logger:ERROR [Errno 95] Operation not supported

timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
timeline_webview:INFO No HTTP thumbnail server found yet... keep waiting...
..continues
```

**Comment by jose1711** [comment]
oops, wrong project. sorry..
